### ISSUE TITLE
Error on trying to configure

### ISSUE THREAD

**Issue by LalitoAlva** [pkp/shibboleth#25]
Hi, I have an 3.3.0.10 installation of OJS, recently i add this plugin but i can't configure it because it shows me a Failed Ajax request or invalid JSON returned.

The log said:

PHP Fatal error:  Declaration of ShibbolethSettingsForm::fetch($request) must be compatible with Form::fetch($request, $template = null, $display = false) in /openjs/ojs/plugins/generic/shibboleth/ShibbolethSettingsForm.inc.php on line 98

Could you help me, please??
I have a Redhat 8.7 with apache 2.4.37 and PHP 8.0

Thanks in advance...

**Comment by ctgraham** [comment]
@wopsononock , this PHP 8 issue looks well-aligned with the work you are already doing for ULS plugins.  Can you review this as well?

**Comment by bbcluny** [comment]
Hi,
when I want to configure the Shibboleth Authentication Plugin, I get the error : Failed Ajax request or invalid JSON returned.
My config is PHP 8, OJS 3.3.0.14
Thanks in advance

**Comment by ctgraham** [comment]
Resolved here: https://github.com/pkp/shibboleth/issues/26
