### ISSUE TITLE
Plugin tickbox not getting enabled

### ISSUE THREAD

**Issue by B5045438** [pkp/shibboleth#3]
Clicking the enable tickbox brings the message "The plugin "Shibboleth Authentication Plugin" has been enabled." to the screen, but the checkbox isn't checked afterwards and can't be disabled.

**Comment by asmecher** [comment]
@B5045438, what version of OJS are you using?

**Comment by B5045438** [comment]
@asmecher 3.1.1

**Comment by asmecher** [comment]
@B5045438, do you intend to use this plugin? Or are you just experimenting?

**Comment by B5045438** [comment]
@asmecher I'm trying to actually use for a registration/login system.

**Comment by asmecher** [comment]
@B5045438, are you running a multi-journal system, or single-journal?

**Comment by B5045438** [comment]
@asmecher Single journal

**Comment by asmecher** [comment]
I think this plugin was written for multi-journal installations. Can you try creating a second journal, going into Site Administration, and enabling the plugin from the Plugins area there?

**Comment by B5045438** [comment]
@asmecher I created a test journal and I was able to finally enable it and access it settings but only in Site Administration.

**Comment by asmecher** [comment]
Hmm, I'm not sure about this plugin's intentions WRT single- vs. multi-journal installations. @crism and @ctgraham, do you recall?

**Comment by crism** [comment]
I think I see the problem. In `LazyLoadPlugin::setEnabled()`, if `isSitePlugin()` is true, then it sets the `enabled` flag for context `0`. The logic in `ShibbolethAuthPlugin` won’t allow per-journal settings if the plugin is enabled site-wide. It seems like we need something like `canBeSitePlugin()` instead…

**Comment by ctgraham** [comment]
I was working with this problem on pkp-lib#1923.

https://github.com/pkp/pkp-lib/issues/1923#issuecomment-260712411

In a lot of cases (like authentication, Google Analytics, etc) I think we want a admin-controlled setting which describes whether the plugin requires configuration at the site level vs. allows overriding at the context level, and a manager-controlled setting which describes whether the plugin should inherit the site settings vs. try implement its own context-specific settings.

**Comment by cpockett** [comment]
Any progress on this? We'd like to use this for our single journal installation as well. I could create a dummy journal but that just feels wrong.

**Comment by ctgraham** [comment]
Should be resolved by #12.

**Comment by ctgraham** [comment]
This issue remains active in single journal installs.

**Comment by ctgraham** [comment]
@davidjb , can you confirm this commit (https://github.com/pkp/shibboleth/commit/3e59e58dcb09ed10e762c073365928bcb9dc05f3) doesn't break anything in multijournal installations?

**Comment by davidjb** [comment]
@ctgraham Looks good to me - everything's fine in my multijournal configuration (login at root level and journal level, config at site-wide level, and ability for only system admins to modify settings at the site level).
