### ISSUE TITLE
`setFirstName` and `setLastName` no longer exist in the Identity data object

### ISSUE THREAD

**Issue by kasioumis** [pkp/shibboleth#9]
Upon a successful login with Shibboleth, and if the user does not already exist, [a new user is created](https://github.com/pkp/shibboleth/blob/master/pages/ShibbolethHandler.inc.php#L164). Among other things, the user's [first name](https://github.com/pkp/shibboleth/blob/master/pages/ShibbolethHandler.inc.php#L373) and [last name](https://github.com/pkp/shibboleth/blob/master/pages/ShibbolethHandler.inc.php#L374) are set (with `setFirstName` and `setLastName` respectively). However, since [pkp-lib's 32d50e1a846d8c9493ec6a1f24661aa0b28371d7 commit](https://github.com/pkp/pkp-lib/commit/32d50e1a846d8c9493ec6a1f24661aa0b28371d7#diff-419721ef540b7f5794daa4482444e8b4), these 2 functions are gone and replaced by (presumably) `setGivenName` and `setFamilyName` in the Identity data object. This results in a `PHP Fatal error:  Uncaught Error: Call to undefined method User::setFirstName()`. Would switching `setFirstName` and `setLastName` for `setGivenName` and `setFamilyName` respectively in [ShibbolethHandler.inc.php](https://github.com/pkp/shibboleth/blob/master/pages/ShibbolethHandler.inc.php) suffice as a fix?

**Comment by kasioumis** [comment]
The following seems to work as expected:
``` PHP
// Get the site primary locale
$request = Application::getRequest();
$site = $request->getSite();
$sitePrimaryLocale = $site->getPrimaryLocale();

// Set the given and family names
$user->setGivenName($userFirstName, $sitePrimaryLocale);
$user->setFamilyName($userLastName, $sitePrimaryLocale);
```
Would that be an acceptable fix?

**Comment by asmecher** [comment]
Yes, @kasioumis -- it looks like this plugin hasn't been adapted for multilingual user/author names (starting in OJS 3.1.2). Could you open a PR with that change?

**Comment by kasioumis** [comment]
@asmecher Sure, here it goes: <https://github.com/pkp/shibboleth/pull/10>. Let me know if it's good to go as is or if it needs any amendments.

**Comment by asmecher** [comment]
Thanks again, @kasioumis!
